# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CapturePictureUI.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(703, 659)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Login_groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.Login_groupBox.setGeometry(QtCore.QRect(10, 10, 681, 101))
        self.Login_groupBox.setObjectName("Login_groupBox")
        self.User_lineEdit = QtWidgets.QLineEdit(self.Login_groupBox)
        self.User_lineEdit.setGeometry(QtCore.QRect(110, 60, 111, 20))
        self.User_lineEdit.setObjectName("User_lineEdit")
        self.Pwd_lineEdit = QtWidgets.QLineEdit(self.Login_groupBox)
        self.Pwd_lineEdit.setGeometry(QtCore.QRect(320, 60, 111, 20))
        self.Pwd_lineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.Pwd_lineEdit.setObjectName("Pwd_lineEdit")
        self.Port_label = QtWidgets.QLabel(self.Login_groupBox)
        self.Port_label.setGeometry(QtCore.QRect(230, 30, 61, 16))
        self.Port_label.setObjectName("Port_label")
        self.IP_label = QtWidgets.QLabel(self.Login_groupBox)
        self.IP_label.setGeometry(QtCore.QRect(10, 30, 61, 16))
        self.IP_label.setObjectName("IP_label")
        self.Port_lineEdit = QtWidgets.QLineEdit(self.Login_groupBox)
        self.Port_lineEdit.setGeometry(QtCore.QRect(320, 30, 111, 20))
        self.Port_lineEdit.setObjectName("Port_lineEdit")
        self.Pwd_label = QtWidgets.QLabel(self.Login_groupBox)
        self.Pwd_label.setGeometry(QtCore.QRect(230, 60, 91, 16))
        self.Pwd_label.setObjectName("Pwd_label")
        self.User_label = QtWidgets.QLabel(self.Login_groupBox)
        self.User_label.setGeometry(QtCore.QRect(3, 60, 101, 20))
        self.User_label.setObjectName("User_label")
        self.IP_lineEdit = QtWidgets.QLineEdit(self.Login_groupBox)
        self.IP_lineEdit.setGeometry(QtCore.QRect(110, 30, 109, 20))
        self.IP_lineEdit.setObjectName("IP_lineEdit")
        self.Login_pushButton = QtWidgets.QPushButton(self.Login_groupBox)
        self.Login_pushButton.setGeometry(QtCore.QRect(450, 40, 91, 31))
        self.Login_pushButton.setObjectName("Login_pushButton")
        self.Logout_pushButton = QtWidgets.QPushButton(self.Login_groupBox)
        self.Logout_pushButton.setGeometry(QtCore.QRect(560, 40, 91, 31))
        self.Logout_pushButton.setObjectName("Logout_pushButton")
        self.Capture_groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.Capture_groupBox.setGeometry(QtCore.QRect(10, 130, 681, 481))
        self.Capture_groupBox.setObjectName("Capture_groupBox")
        self.Channel_label = QtWidgets.QLabel(self.Capture_groupBox)
        self.Channel_label.setGeometry(QtCore.QRect(10, 20, 81, 16))
        self.Channel_label.setObjectName("Channel_label")
        self.Channel_comboBox = QtWidgets.QComboBox(self.Capture_groupBox)
        self.Channel_comboBox.setGeometry(QtCore.QRect(100, 20, 69, 22))
        self.Channel_comboBox.setObjectName("Channel_comboBox")
        self.Capture_pushButton = QtWidgets.QPushButton(self.Capture_groupBox)
        self.Capture_pushButton.setGeometry(QtCore.QRect(210, 12, 111, 31))
        self.Capture_pushButton.setObjectName("Capture_pushButton")
        self.Picture_label = QtWidgets.QLabel(self.Capture_groupBox)
        self.Picture_label.setGeometry(QtCore.QRect(20, 50, 641, 411))
        self.Picture_label.setStyleSheet("background-color: rgb(202, 202, 202);")
        self.Picture_label.setText("")
        self.Picture_label.setObjectName("Picture_label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 703, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.Switch_action = QtWidgets.QAction(MainWindow)
        self.Switch_action.setObjectName("Switch_action")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "抓图(Capture)-离线(OffLine)"))
        self.Login_groupBox.setTitle(_translate("MainWindow", "登录信息(Login info)"))
        self.Port_label.setText(_translate("MainWindow", "端口(Port)"))
        self.IP_label.setText(_translate("MainWindow", "IP地址(IP)"))
        self.Pwd_label.setText(_translate("MainWindow", "密码(Password)"))
        self.User_label.setText(_translate("MainWindow", "用户名(Username)"))
        self.Login_pushButton.setText(_translate("MainWindow", "登录(Login)"))
        self.Logout_pushButton.setText(_translate("MainWindow", "登出(Logout)"))
        self.Capture_groupBox.setTitle(_translate("MainWindow", "抓图(Capture)"))
        self.Channel_label.setText(_translate("MainWindow", "通道(Channel)"))
        self.Capture_pushButton.setText(_translate("MainWindow", "抓图(Capture)"))
        self.Switch_action.setText(_translate("MainWindow", "中英文切换"))

