# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FaceRecognitionUI.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(845, 646)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(0, 10, 841, 55))
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(190, 22, 60, 16))
        self.label.setObjectName("label")
        self.Port_lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.Port_lineEdit.setEnabled(True)
        self.Port_lineEdit.setGeometry(QtCore.QRect(260, 20, 61, 20))
        self.Port_lineEdit.setText("")
        self.Port_lineEdit.setObjectName("Port_lineEdit")
        self.Name_lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.Name_lineEdit.setGeometry(QtCore.QRect(420, 20, 100, 20))
        self.Name_lineEdit.setObjectName("Name_lineEdit")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(340, 20, 91, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(10, 22, 60, 16))
        self.label_3.setObjectName("label_3")
        self.IP_lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.IP_lineEdit.setGeometry(QtCore.QRect(80, 23, 101, 20))
        self.IP_lineEdit.setText("")
        self.IP_lineEdit.setObjectName("IP_lineEdit")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(540, 22, 54, 16))
        self.label_4.setObjectName("label_4")
        self.Pwd_lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.Pwd_lineEdit.setGeometry(QtCore.QRect(600, 20, 100, 20))
        self.Pwd_lineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.Pwd_lineEdit.setObjectName("Pwd_lineEdit")
        self.Login_pushButton = QtWidgets.QPushButton(self.groupBox)
        self.Login_pushButton.setGeometry(QtCore.QRect(730, 20, 101, 31))
        self.Login_pushButton.setObjectName("Login_pushButton")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(0, 70, 551, 55))
        self.groupBox_3.setObjectName("groupBox_3")
        self.Channel_comboBox = QtWidgets.QComboBox(self.groupBox_3)
        self.Channel_comboBox.setGeometry(QtCore.QRect(100, 20, 91, 21))
        self.Channel_comboBox.setObjectName("Channel_comboBox")
        self.label_5 = QtWidgets.QLabel(self.groupBox_3)
        self.label_5.setGeometry(QtCore.QRect(20, 20, 81, 16))
        self.label_5.setObjectName("label_5")
        self.ListenEvent_pushButton = QtWidgets.QPushButton(self.groupBox_3)
        self.ListenEvent_pushButton.setEnabled(False)
        self.ListenEvent_pushButton.setGeometry(QtCore.QRect(380, 20, 151, 31))
        self.ListenEvent_pushButton.setObjectName("ListenEvent_pushButton")
        self.Play_pushButton = QtWidgets.QPushButton(self.groupBox_3)
        self.Play_pushButton.setEnabled(False)
        self.Play_pushButton.setGeometry(QtCore.QRect(230, 20, 111, 31))
        self.Play_pushButton.setObjectName("Play_pushButton")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(0, 130, 411, 271))
        self.groupBox_2.setObjectName("groupBox_2")
        self.Play_wnd = QtWidgets.QLabel(self.groupBox_2)
        self.Play_wnd.setGeometry(QtCore.QRect(10, 20, 381, 241))
        self.Play_wnd.setStyleSheet("background-color: rgb(180, 180, 180);")
        self.Play_wnd.setText("")
        self.Play_wnd.setAlignment(QtCore.Qt.AlignCenter)
        self.Play_wnd.setObjectName("Play_wnd")
        self.GlobalImg_groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.GlobalImg_groupBox.setGeometry(QtCore.QRect(420, 130, 421, 271))
        self.GlobalImg_groupBox.setObjectName("GlobalImg_groupBox")
        self.GlobalImg_wnd = QtWidgets.QLabel(self.GlobalImg_groupBox)
        self.GlobalImg_wnd.setGeometry(QtCore.QRect(10, 20, 401, 241))
        self.GlobalImg_wnd.setStyleSheet("background-color: rgb(180, 180, 180);")
        self.GlobalImg_wnd.setText("")
        self.GlobalImg_wnd.setObjectName("GlobalImg_wnd")
        self.FaceImg_groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.FaceImg_groupBox.setGeometry(QtCore.QRect(0, 410, 411, 191))
        self.FaceImg_groupBox.setObjectName("FaceImg_groupBox")
        self.FaceImg_wnd = QtWidgets.QLabel(self.FaceImg_groupBox)
        self.FaceImg_wnd.setGeometry(QtCore.QRect(10, 20, 171, 161))
        self.FaceImg_wnd.setStyleSheet("background-color: rgb(180, 180, 180);")
        self.FaceImg_wnd.setLineWidth(0)
        self.FaceImg_wnd.setText("")
        self.FaceImg_wnd.setObjectName("FaceImg_wnd")
        self.label_14 = QtWidgets.QLabel(self.FaceImg_groupBox)
        self.label_14.setGeometry(QtCore.QRect(210, 30, 71, 16))
        self.label_14.setObjectName("label_14")
        self.face_time_label = QtWidgets.QLabel(self.FaceImg_groupBox)
        self.face_time_label.setGeometry(QtCore.QRect(280, 30, 131, 16))
        self.face_time_label.setObjectName("face_time_label")
        self.label_10 = QtWidgets.QLabel(self.FaceImg_groupBox)
        self.label_10.setGeometry(QtCore.QRect(210, 50, 71, 16))
        self.label_10.setObjectName("label_10")
        self.face_sex_label = QtWidgets.QLabel(self.FaceImg_groupBox)
        self.face_sex_label.setGeometry(QtCore.QRect(280, 50, 131, 16))
        self.face_sex_label.setObjectName("face_sex_label")
        self.label_11 = QtWidgets.QLabel(self.FaceImg_groupBox)
        self.label_11.setGeometry(QtCore.QRect(210, 70, 71, 16))
        self.label_11.setObjectName("label_11")
        self.face_age_label = QtWidgets.QLabel(self.FaceImg_groupBox)
        self.face_age_label.setGeometry(QtCore.QRect(280, 70, 131, 16))
        self.face_age_label.setObjectName("face_age_label")
        self.label_15 = QtWidgets.QLabel(self.FaceImg_groupBox)
        self.label_15.setGeometry(QtCore.QRect(210, 90, 71, 16))
        self.label_15.setObjectName("label_15")
        self.face_race_label = QtWidgets.QLabel(self.FaceImg_groupBox)
        self.face_race_label.setGeometry(QtCore.QRect(280, 90, 131, 16))
        self.face_race_label.setObjectName("face_race_label")
        self.label_17 = QtWidgets.QLabel(self.FaceImg_groupBox)
        self.label_17.setGeometry(QtCore.QRect(210, 110, 71, 16))
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.FaceImg_groupBox)
        self.label_18.setGeometry(QtCore.QRect(200, 130, 81, 16))
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.FaceImg_groupBox)
        self.label_19.setGeometry(QtCore.QRect(210, 150, 71, 16))
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.FaceImg_groupBox)
        self.label_20.setGeometry(QtCore.QRect(200, 170, 91, 16))
        self.label_20.setObjectName("label_20")
        self.face_eye_label = QtWidgets.QLabel(self.FaceImg_groupBox)
        self.face_eye_label.setGeometry(QtCore.QRect(280, 110, 131, 16))
        self.face_eye_label.setObjectName("face_eye_label")
        self.face_mouth_label = QtWidgets.QLabel(self.FaceImg_groupBox)
        self.face_mouth_label.setGeometry(QtCore.QRect(280, 130, 121, 16))
        self.face_mouth_label.setObjectName("face_mouth_label")
        self.face_mask_label = QtWidgets.QLabel(self.FaceImg_groupBox)
        self.face_mask_label.setGeometry(QtCore.QRect(280, 150, 131, 16))
        self.face_mask_label.setObjectName("face_mask_label")
        self.face_beard_label = QtWidgets.QLabel(self.FaceImg_groupBox)
        self.face_beard_label.setGeometry(QtCore.QRect(280, 170, 131, 16))
        self.face_beard_label.setObjectName("face_beard_label")
        self.CandidateImg_groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.CandidateImg_groupBox.setGeometry(QtCore.QRect(420, 410, 421, 191))
        self.CandidateImg_groupBox.setObjectName("CandidateImg_groupBox")
        self.CandidateImg_wnd = QtWidgets.QLabel(self.CandidateImg_groupBox)
        self.CandidateImg_wnd.setGeometry(QtCore.QRect(10, 20, 151, 161))
        self.CandidateImg_wnd.setStyleSheet("background-color: rgb(180, 180, 180);")
        self.CandidateImg_wnd.setText("")
        self.CandidateImg_wnd.setObjectName("CandidateImg_wnd")
        self.label_25 = QtWidgets.QLabel(self.CandidateImg_groupBox)
        self.label_25.setGeometry(QtCore.QRect(220, 30, 81, 16))
        self.label_25.setObjectName("label_25")
        self.candidate_name_label = QtWidgets.QLabel(self.CandidateImg_groupBox)
        self.candidate_name_label.setGeometry(QtCore.QRect(300, 30, 121, 16))
        self.candidate_name_label.setObjectName("candidate_name_label")
        self.label_27 = QtWidgets.QLabel(self.CandidateImg_groupBox)
        self.label_27.setGeometry(QtCore.QRect(230, 50, 71, 16))
        self.label_27.setObjectName("label_27")
        self.candidate_sex_label = QtWidgets.QLabel(self.CandidateImg_groupBox)
        self.candidate_sex_label.setGeometry(QtCore.QRect(300, 50, 121, 16))
        self.candidate_sex_label.setObjectName("candidate_sex_label")
        self.label_29 = QtWidgets.QLabel(self.CandidateImg_groupBox)
        self.label_29.setGeometry(QtCore.QRect(220, 70, 71, 16))
        self.label_29.setObjectName("label_29")
        self.candidate_birth_label = QtWidgets.QLabel(self.CandidateImg_groupBox)
        self.candidate_birth_label.setGeometry(QtCore.QRect(300, 70, 121, 16))
        self.candidate_birth_label.setObjectName("candidate_birth_label")
        self.label_30 = QtWidgets.QLabel(self.CandidateImg_groupBox)
        self.label_30.setGeometry(QtCore.QRect(220, 90, 81, 16))
        self.label_30.setObjectName("label_30")
        self.candidate_id_label = QtWidgets.QLabel(self.CandidateImg_groupBox)
        self.candidate_id_label.setGeometry(QtCore.QRect(300, 90, 121, 16))
        self.candidate_id_label.setObjectName("candidate_id_label")
        self.label_32 = QtWidgets.QLabel(self.CandidateImg_groupBox)
        self.label_32.setGeometry(QtCore.QRect(160, 110, 141, 20))
        self.label_32.setObjectName("label_32")
        self.label_33 = QtWidgets.QLabel(self.CandidateImg_groupBox)
        self.label_33.setGeometry(QtCore.QRect(160, 130, 141, 16))
        self.label_33.setObjectName("label_33")
        self.label_34 = QtWidgets.QLabel(self.CandidateImg_groupBox)
        self.label_34.setGeometry(QtCore.QRect(180, 150, 121, 16))
        self.label_34.setObjectName("label_34")
        self.candidate_library_no_label = QtWidgets.QLabel(self.CandidateImg_groupBox)
        self.candidate_library_no_label.setGeometry(QtCore.QRect(300, 110, 121, 16))
        self.candidate_library_no_label.setObjectName("candidate_library_no_label")
        self.candidate_library_name_label = QtWidgets.QLabel(self.CandidateImg_groupBox)
        self.candidate_library_name_label.setGeometry(QtCore.QRect(300, 130, 121, 16))
        self.candidate_library_name_label.setObjectName("candidate_library_name_label")
        self.candidate_similarity_label = QtWidgets.QLabel(self.CandidateImg_groupBox)
        self.candidate_similarity_label.setGeometry(QtCore.QRect(300, 150, 121, 16))
        self.candidate_similarity_label.setObjectName("candidate_similarity_label")
        self.FaceImg_groupBox.raise_()
        self.groupBox.raise_()
        self.groupBox_3.raise_()
        self.groupBox_2.raise_()
        self.GlobalImg_groupBox.raise_()
        self.CandidateImg_groupBox.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 845, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "人脸识别(FaceRecognition)"))
        self.groupBox.setTitle(_translate("MainWindow", "设备登录(Device Login)"))
        self.label.setText(_translate("MainWindow", "端口(Port)"))
        self.label_2.setText(_translate("MainWindow", "用户名(Name)"))
        self.label_3.setText(_translate("MainWindow", "IP地址(IP)"))
        self.label_4.setText(_translate("MainWindow", "密码(PWD)"))
        self.Login_pushButton.setText(_translate("MainWindow", "登录(Login)"))
        self.groupBox_3.setTitle(_translate("MainWindow", "订阅操作(Listen Event)"))
        self.label_5.setText(_translate("MainWindow", "通道(channel)"))
        self.ListenEvent_pushButton.setText(_translate("MainWindow", "订阅事件(Listen Event)"))
        self.Play_pushButton.setText(_translate("MainWindow", "监视(Play)"))
        self.groupBox_2.setTitle(_translate("MainWindow", "实时监视(RealPlay)"))
        self.GlobalImg_groupBox.setTitle(_translate("MainWindow", "全景图(Global Picture)"))
        self.FaceImg_groupBox.setTitle(_translate("MainWindow", "人脸图(Face Picture)"))
        self.label_14.setText(_translate("MainWindow", "时间(time):"))
        self.face_time_label.setText(_translate("MainWindow", "123123"))
        self.label_10.setText(_translate("MainWindow", "性别(sex):"))
        self.face_sex_label.setText(_translate("MainWindow", "123123"))
        self.label_11.setText(_translate("MainWindow", "年龄(age):"))
        self.face_age_label.setText(_translate("MainWindow", "123123"))
        self.label_15.setText(_translate("MainWindow", "肤色(race):"))
        self.face_race_label.setText(_translate("MainWindow", "123123"))
        self.label_17.setText(_translate("MainWindow", "眼睛(eye):"))
        self.label_18.setText(_translate("MainWindow", "嘴巴(mouth):"))
        self.label_19.setText(_translate("MainWindow", "口罩(mask):"))
        self.label_20.setText(_translate("MainWindow", "胡子(beard):"))
        self.face_eye_label.setText(_translate("MainWindow", "123123"))
        self.face_mouth_label.setText(_translate("MainWindow", "123123"))
        self.face_mask_label.setText(_translate("MainWindow", "123123"))
        self.face_beard_label.setText(_translate("MainWindow", "123123"))
        self.CandidateImg_groupBox.setTitle(_translate("MainWindow", "候选图(Candidate Picture)"))
        self.label_25.setText(_translate("MainWindow", "姓名(name):"))
        self.candidate_name_label.setText(_translate("MainWindow", "123123"))
        self.label_27.setText(_translate("MainWindow", "性别(sex):"))
        self.candidate_sex_label.setText(_translate("MainWindow", "123123"))
        self.label_29.setText(_translate("MainWindow", "生日(birth):"))
        self.candidate_birth_label.setText(_translate("MainWindow", "123123"))
        self.label_30.setText(_translate("MainWindow", " 证件号(id):"))
        self.candidate_id_label.setText(_translate("MainWindow", "123123"))
        self.label_32.setText(_translate("MainWindow", " 人脸库序号(group id):"))
        self.label_33.setText(_translate("MainWindow", " 人脸库名(group name):"))
        self.label_34.setText(_translate("MainWindow", "相似度(similarity):"))
        self.candidate_library_no_label.setText(_translate("MainWindow", "123123"))
        self.candidate_library_name_label.setText(_translate("MainWindow", "123123"))
        self.candidate_similarity_label.setText(_translate("MainWindow", "123123"))

