# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'IntelligentTrafficUI.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(923, 668)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Login_groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.Login_groupBox.setGeometry(QtCore.QRect(10, 10, 901, 61))
        self.Login_groupBox.setObjectName("Login_groupBox")
        self.Logout_pushButton = QtWidgets.QPushButton(self.Login_groupBox)
        self.Logout_pushButton.setGeometry(QtCore.QRect(800, 20, 91, 41))
        self.Logout_pushButton.setObjectName("Logout_pushButton")
        self.Login_pushButton = QtWidgets.QPushButton(self.Login_groupBox)
        self.Login_pushButton.setGeometry(QtCore.QRect(700, 20, 91, 41))
        self.Login_pushButton.setObjectName("Login_pushButton")
        self.Pwd_label = QtWidgets.QLabel(self.Login_groupBox)
        self.Pwd_label.setGeometry(QtCore.QRect(510, 30, 91, 20))
        self.Pwd_label.setObjectName("Pwd_label")
        self.User_label = QtWidgets.QLabel(self.Login_groupBox)
        self.User_label.setGeometry(QtCore.QRect(310, 30, 111, 20))
        self.User_label.setObjectName("User_label")
        self.Port_lineEdit = QtWidgets.QLineEdit(self.Login_groupBox)
        self.Port_lineEdit.setGeometry(QtCore.QRect(240, 30, 71, 20))
        self.Port_lineEdit.setObjectName("Port_lineEdit")
        self.User_lineEdit = QtWidgets.QLineEdit(self.Login_groupBox)
        self.User_lineEdit.setGeometry(QtCore.QRect(410, 30, 91, 20))
        self.User_lineEdit.setObjectName("User_lineEdit")
        self.Pwd_lineEdit = QtWidgets.QLineEdit(self.Login_groupBox)
        self.Pwd_lineEdit.setGeometry(QtCore.QRect(600, 30, 91, 20))
        self.Pwd_lineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.Pwd_lineEdit.setObjectName("Pwd_lineEdit")
        self.IP_label = QtWidgets.QLabel(self.Login_groupBox)
        self.IP_label.setGeometry(QtCore.QRect(0, 30, 81, 16))
        self.IP_label.setObjectName("IP_label")
        self.IP_lineEdit = QtWidgets.QLineEdit(self.Login_groupBox)
        self.IP_lineEdit.setGeometry(QtCore.QRect(60, 30, 111, 20))
        self.IP_lineEdit.setObjectName("IP_lineEdit")
        self.Port_label = QtWidgets.QLabel(self.Login_groupBox)
        self.Port_label.setGeometry(QtCore.QRect(180, 30, 61, 16))
        self.Port_label.setObjectName("Port_label")
        self.Operate_groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.Operate_groupBox.setGeometry(QtCore.QRect(10, 80, 201, 271))
        self.Operate_groupBox.setObjectName("Operate_groupBox")
        self.Play_pushButton = QtWidgets.QPushButton(self.Operate_groupBox)
        self.Play_pushButton.setGeometry(QtCore.QRect(10, 80, 191, 31))
        self.Play_pushButton.setObjectName("Play_pushButton")
        self.StopPlay_pushButton = QtWidgets.QPushButton(self.Operate_groupBox)
        self.StopPlay_pushButton.setGeometry(QtCore.QRect(10, 130, 191, 31))
        self.StopPlay_pushButton.setObjectName("StopPlay_pushButton")
        self.Attach_pushButton = QtWidgets.QPushButton(self.Operate_groupBox)
        self.Attach_pushButton.setGeometry(QtCore.QRect(10, 180, 191, 31))
        self.Attach_pushButton.setObjectName("Attach_pushButton")
        self.Detach_pushButton = QtWidgets.QPushButton(self.Operate_groupBox)
        self.Detach_pushButton.setGeometry(QtCore.QRect(10, 230, 191, 31))
        self.Detach_pushButton.setObjectName("Detach_pushButton")
        self.Channel_comboBox = QtWidgets.QComboBox(self.Operate_groupBox)
        self.Channel_comboBox.setGeometry(QtCore.QRect(100, 40, 91, 22))
        self.Channel_comboBox.setObjectName("Channel_comboBox")
        self.label = QtWidgets.QLabel(self.Operate_groupBox)
        self.label.setGeometry(QtCore.QRect(10, 40, 101, 16))
        self.label.setObjectName("label")
        self.Play_groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.Play_groupBox.setGeometry(QtCore.QRect(210, 80, 391, 271))
        self.Play_groupBox.setObjectName("Play_groupBox")
        self.Video_label = QtWidgets.QLabel(self.Play_groupBox)
        self.Video_label.setGeometry(QtCore.QRect(10, 20, 371, 241))
        self.Video_label.setStyleSheet("background-color: rgb(189, 189, 189);")
        self.Video_label.setText("")
        self.Video_label.setObjectName("Video_label")
        self.Attach_groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.Attach_groupBox.setGeometry(QtCore.QRect(10, 350, 591, 271))
        self.Attach_groupBox.setObjectName("Attach_groupBox")
        self.Attach_tableWidget = QtWidgets.QTableWidget(self.Attach_groupBox)
        self.Attach_tableWidget.setGeometry(QtCore.QRect(10, 20, 571, 241))
        self.Attach_tableWidget.setObjectName("Attach_tableWidget")
        self.Attach_tableWidget.setColumnCount(6)
        self.Attach_tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.Attach_tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.Attach_tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.Attach_tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.Attach_tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.Attach_tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.Attach_tableWidget.setHorizontalHeaderItem(5, item)
        self.Attach_tableWidget.horizontalHeader().setDefaultSectionSize(150)
        self.GlobalScene_label = QtWidgets.QLabel(self.centralwidget)
        self.GlobalScene_label.setGeometry(QtCore.QRect(620, 100, 281, 241))
        self.GlobalScene_label.setStyleSheet("background-color: rgb(189, 189, 189);")
        self.GlobalScene_label.setText("")
        self.GlobalScene_label.setObjectName("GlobalScene_label")
        self.GlobalScene_groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.GlobalScene_groupBox.setGeometry(QtCore.QRect(610, 80, 301, 271))
        self.GlobalScene_groupBox.setObjectName("GlobalScene_groupBox")
        self.VehicleInfo_groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.VehicleInfo_groupBox.setGeometry(QtCore.QRect(610, 350, 301, 271))
        self.VehicleInfo_groupBox.setObjectName("VehicleInfo_groupBox")
        self.SmallScene_label = QtWidgets.QLabel(self.VehicleInfo_groupBox)
        self.SmallScene_label.setGeometry(QtCore.QRect(30, 70, 251, 81))
        self.SmallScene_label.setStyleSheet("background-color: rgb(189, 189, 189);")
        self.SmallScene_label.setText("")
        self.SmallScene_label.setObjectName("SmallScene_label")
        self.VehicleInfo_groupBox.raise_()
        self.GlobalScene_groupBox.raise_()
        self.Operate_groupBox.raise_()
        self.Login_groupBox.raise_()
        self.Play_groupBox.raise_()
        self.Attach_groupBox.raise_()
        self.GlobalScene_label.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 923, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.Switch_action = QtWidgets.QAction(MainWindow)
        self.Switch_action.setObjectName("Switch_action")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "智能交通(IntelligentTraffic)-离线(Offline)"))
        self.Login_groupBox.setTitle(_translate("MainWindow", "设备登录(Login info)"))
        self.Logout_pushButton.setText(_translate("MainWindow", "登出(Logout)"))
        self.Login_pushButton.setText(_translate("MainWindow", "登录(Login)"))
        self.Pwd_label.setText(_translate("MainWindow", "密码(Password)"))
        self.User_label.setText(_translate("MainWindow", "用户名(Username)"))
        self.IP_label.setText(_translate("MainWindow", "IP地址(IP)"))
        self.Port_label.setText(_translate("MainWindow", "端口(Port)"))
        self.Operate_groupBox.setTitle(_translate("MainWindow", "操作（Operation）"))
        self.Play_pushButton.setText(_translate("MainWindow", "监视(Start Monitoring)"))
        self.StopPlay_pushButton.setText(_translate("MainWindow", "停止监视（Stop Monitoring）"))
        self.Attach_pushButton.setText(_translate("MainWindow", "订阅（Subscribe）"))
        self.Detach_pushButton.setText(_translate("MainWindow", "停止订阅（Cancel Subscription）"))
        self.label.setText(_translate("MainWindow", "通道（Channel)"))
        self.Play_groupBox.setTitle(_translate("MainWindow", "播放（Play）"))
        self.Attach_groupBox.setTitle(_translate("MainWindow", "订阅信息(Subscription  Details)"))
        item = self.Attach_tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "时间(Time)"))
        item = self.Attach_tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "事件(Event)"))
        item = self.Attach_tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "车牌号(Plate No.)"))
        item = self.Attach_tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "车牌颜色(Plate Color)"))
        item = self.Attach_tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "车型类型(Vehicle Type)"))
        item = self.Attach_tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "车身颜色(Vehicle Color)"))
        self.GlobalScene_groupBox.setTitle(_translate("MainWindow", "全景图（Panoramic Image）"))
        self.VehicleInfo_groupBox.setTitle(_translate("MainWindow", "车牌图（Plate Image)"))
        self.Switch_action.setText(_translate("MainWindow", "中英文切换"))

