# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DeviceControlUI.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(589, 307)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 561, 101))
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(20, 30, 71, 16))
        self.label.setObjectName("label")
        self.IP_lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.IP_lineEdit.setGeometry(QtCore.QRect(90, 30, 121, 20))
        self.IP_lineEdit.setObjectName("IP_lineEdit")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(240, 30, 71, 16))
        self.label_2.setObjectName("label_2")
        self.Port_lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.Port_lineEdit.setGeometry(QtCore.QRect(310, 30, 113, 20))
        self.Port_lineEdit.setObjectName("Port_lineEdit")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(10, 70, 71, 16))
        self.label_3.setObjectName("label_3")
        self.Name_lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.Name_lineEdit.setGeometry(QtCore.QRect(90, 70, 121, 20))
        self.Name_lineEdit.setObjectName("Name_lineEdit")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(240, 70, 101, 16))
        self.label_4.setObjectName("label_4")
        self.Pwd_lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.Pwd_lineEdit.setGeometry(QtCore.QRect(310, 70, 113, 20))
        self.Pwd_lineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.Pwd_lineEdit.setObjectName("Pwd_lineEdit")
        self.Login_pushButton = QtWidgets.QPushButton(self.groupBox)
        self.Login_pushButton.setGeometry(QtCore.QRect(460, 30, 91, 31))
        self.Login_pushButton.setObjectName("Login_pushButton")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 200, 571, 61))
        self.groupBox_2.setObjectName("groupBox_2")
        self.GetTime_pushButton = QtWidgets.QPushButton(self.groupBox_2)
        self.GetTime_pushButton.setGeometry(QtCore.QRect(330, 30, 75, 23))
        self.GetTime_pushButton.setObjectName("GetTime_pushButton")
        self.SetTime_pushButton = QtWidgets.QPushButton(self.groupBox_2)
        self.SetTime_pushButton.setGeometry(QtCore.QRect(430, 30, 75, 23))
        self.SetTime_pushButton.setObjectName("SetTime_pushButton")
        self.Time_dateTimeEdit = QtWidgets.QDateTimeEdit(self.groupBox_2)
        self.Time_dateTimeEdit.setGeometry(QtCore.QRect(90, 30, 191, 22))
        self.Time_dateTimeEdit.setDateTime(QtCore.QDateTime(QtCore.QDate(2020, 3, 16), QtCore.QTime(0, 0, 0)))
        self.Time_dateTimeEdit.setObjectName("Time_dateTimeEdit")
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(20, 30, 71, 16))
        self.label_5.setObjectName("label_5")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(370, 120, 211, 71))
        self.groupBox_3.setObjectName("groupBox_3")
        self.Restart_pushButton = QtWidgets.QPushButton(self.groupBox_3)
        self.Restart_pushButton.setGeometry(QtCore.QRect(50, 20, 111, 31))
        self.Restart_pushButton.setObjectName("Restart_pushButton")
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 120, 221, 71))
        self.groupBox_4.setObjectName("groupBox_4")
        self.CloseLog_pushButton = QtWidgets.QPushButton(self.groupBox_4)
        self.CloseLog_pushButton.setGeometry(QtCore.QRect(110, 30, 75, 23))
        self.CloseLog_pushButton.setObjectName("CloseLog_pushButton")
        self.OpenLog_pushButton = QtWidgets.QPushButton(self.groupBox_4)
        self.OpenLog_pushButton.setGeometry(QtCore.QRect(20, 30, 75, 23))
        self.OpenLog_pushButton.setObjectName("OpenLog_pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 589, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "设备控制(DeviceControl)"))
        self.groupBox.setTitle(_translate("MainWindow", "设备登录(Device Login)"))
        self.label.setText(_translate("MainWindow", "IP地址(IP)"))
        self.label_2.setText(_translate("MainWindow", "端口(Port)"))
        self.label_3.setText(_translate("MainWindow", "用户名(Name)"))
        self.label_4.setText(_translate("MainWindow", "密码(PWD)"))
        self.Login_pushButton.setText(_translate("MainWindow", "登录(Login)"))
        self.groupBox_2.setTitle(_translate("MainWindow", "校时(Calibration time)"))
        self.GetTime_pushButton.setText(_translate("MainWindow", "获取(get)"))
        self.SetTime_pushButton.setText(_translate("MainWindow", "设置(set)"))
        self.Time_dateTimeEdit.setDisplayFormat(_translate("MainWindow", "yyyy/M/d HH:mm:ss"))
        self.label_5.setText(_translate("MainWindow", "时间(Time)"))
        self.groupBox_3.setTitle(_translate("MainWindow", "远程重启(Remote restart)"))
        self.Restart_pushButton.setText(_translate("MainWindow", "设备重启(restart)"))
        self.groupBox_4.setTitle(_translate("MainWindow", "日志输出(Log output)"))
        self.CloseLog_pushButton.setText(_translate("MainWindow", "关闭(close)"))
        self.OpenLog_pushButton.setText(_translate("MainWindow", "打开(Open)"))

